### ISSUE TITLE
关于 Npm 包名

### ISSUE THREAD

**Issue by aui** [gimm/gulp-font-spider#1]
hi, gimm.

我是 font-spier 的作者，我和小伙伴已经开发完 gulp 插件版本准备发布到 npm 上，但是我发现 npm 上的项目名被您占用了，并且您没有完成这个程序……如果您不打算开发，希望您能够转让 npm 上的包名给我们来维护，谢谢！

**Comment by gimm** [comment]
好的，怎么转给你们？

**Comment by aui** [comment]
你可以试试`unpublish `命令：
```
npm unpublish gulp-font-spider
```

**Comment by gimm** [comment]
已经删除了，你可以发布了。
之前看到你们没做gulp的插件，打算做一个的，看了下代码，发现你们的套路和gulp的流有点出入，就搁置了。

**Comment by aui** [comment]
感谢！我们的包已经推送到 npm 了，也欢迎一起维护
